### ISSUE TITLE
Multithreading options

### ISSUE THREAD

**Issue by ateixeira0163** [polyfem/polyfem#141]
Hi! First of all, great software! 

So, I would like to know if there's a multithreading option for PolyFEM with contact (IPC). I searched in the articles and some code and only found the package TBB, but I didn't quite understand if it is possible to enforce multithreading or single threading for a simulation. 
I'm using the code for large simulations and it would be quite nice to have this options.

Thanks!

**Comment by teseoch** [comment]
by default, it uses tbb and all available threads. You can use `--max_threads` command line argument to specify the number of threads used. The IPC toolkit uses TBB only for parallelization, while polyfem has different options (NONE, TBB, CPP) that can be changed from the cmake with the `POLYFEM_THREADING` option.

Long story short, it is parallel and you can limit the number of threads with `--max_threads <n>`.
