### ISSUE TITLE
Saving deformed result as .msh file

### ISSUE THREAD

**Issue by antonagafonov** [polyfem/polyfem#163]
Hi,
After the simulation, could the deformed version be saved into mesh or msh file?
thanks

**Platform**
- [ ] Windows
- [ ] macOS
- [x] Linux

**Comment by zfergus** [comment]
Not currently, right now you can only export to VTU format. You can then use the python library MeshIO to convert formats. 

We recently added a class for the MSHWriter but it is not used. If you are interested you can try to modify the code to call this writer as well.

**Comment by antonagafonov** [comment]
Thanks
