### ISSUE TITLE
boundary conditions selection without bc_setter

### ISSUE THREAD

**Issue by antonagafonov** [polyfem/polyfem#169]
Hello,
I am willing to implement custom boundary condition selection.
I am creating *.txt file as bc_setter and I see that bc_setter outputs bc for face, but *.msh file is nodes and elements (tetrahedrons in my case).
I want to understand faces correspondence so I can insert custom bc.
Each tetrahedral has 4 faces and there are faces that are shared between tetrahedral, so what is the arrangement of faces in *.txt file based on tetrahedral elements?

Thanks

**Comment by antonagafonov** [comment]
Hi,
SO I loaded the *.msh file with meshio and created faces from tetrohedrals.
Number of faces I created is the same is number in file that bc_setter creating, but the arrangement is not correct.

here my python implementation of the faces creation:

def create_faces_from_tet(tet_msh):
	# input: tet_msh: list of tetrahedrons
	# output: faces: list of faces
	faces = []
	for tet in tet_msh:

		f_0 = [tet[0],tet[1],tet[2]]
		f_0.sort()
		if  f_0 not in faces:
			faces.append(f_0)
		f_1=[tet[0],tet[1],tet[3]]
		f_1.sort()
		if  f_1 not in faces:
			faces.append(f_1)
		f_2=[tet[0],tet[2],tet[3]]
		f_2.sort()
		if  f_2 not in faces:
			faces.append(f_2)
		f_3=[tet[1],tet[2],tet[3]]
		f_3.sort()
		if  f_3 not in faces:
			faces.append(f_3)	
			
	return faces

I think that I need to understand the arrangement of faces selection while building faces file.

Thanks

**Comment by antonagafonov** [comment]
How can I modify bc_setter, such that it will output another *.txt file with vertices indexes in each line, that fits the original file that it outputs?

**Comment by antonagafonov** [comment]
In line 167 of the bc_setter.cpp I think there is an assignment of bc indexes to the face.
Can I create here *.txt file with appropriate face vertecies indecies?

Something like:
![Screenshot from 2023-01-30 15-47-10](https://user-images.githubusercontent.com/63194980/215494640-41dab5c5-c99f-4c28-9446-5a4cb1b49e8e.png)

**Comment by antonagafonov** [comment]
For now found very awkward way to find outer surface face vertices correspondence:

Printing from bc_setter all faces and vertices which are outer.

![Screenshot from 2023-01-30 17-40-25](https://user-images.githubusercontent.com/63194980/215522843-8b5ec05f-239b-4e4b-b9f4-3d668f241492.png)

Printing std to file , from this file I know the correspondence.
Attached file for example.


[cylinder_1_1_0.250.025_bc_output.txt](https://github.com/polyfem/polyfem/files/10537274/cylinder_1_1_0.250.025_bc_output.txt)

**Comment by zfergus** [comment]
I think there is a newer txt format where gou can spcify the vertex ids of the face and the boundary id per line. Perhaps @teseoch can explain exactly how to specify the boundary ids in this format.

**Comment by teseoch** [comment]
the new format is `sidesetid vid1 vdi2 vid3` where `vidi` are the vertices id in the input mesh and `sidesetid` is the id of selection. The reason why we use `vid` instead of `fid` is that the faces are not explicit in the input msh

**Comment by antonagafonov** [comment]
Thanks,
I will try to work with this format.

**Comment by antonagafonov** [comment]
Hi,
Is `sidesetid` can be an arbitrary number?

Thanks

**Comment by antonagafonov** [comment]
Hello, 
I am wondering,is it possible to apply boundary conditions on single vertecies?

**Comment by antonagafonov** [comment]
Hi,
Tring to apply boundary conditions per vertex and having trouble.
I created bc fie were index "1" is for dirichlet_boundary and other "2,3,4, etc." are for the force applied vertices.
Getting error that says, "Static problem need to have some Dirichlet nodes!"

Attached .json file for the simulation and bc file also the error screenshot.

Please help me to understand were my mistake is.
Thanks ,
AA
![Screenshot from 2023-03-19 12-55-33](https://user-images.githubusercontent.com/63194980/226170710-b571e035-6e2e-4e34-b6d3-7e980b87baf2.png)

**Comment by antonagafonov** [comment]
I still didn't get how to select vertices for Dirichlet boundary conditions...
Tried to change to "point_selection" like this:

    "geometry": {
        "mesh": "/home/aa/Documents/GitHub/POLYFEM-DIR/deformable_obj/input_files/meshes/SMPL_LEFT_arm_div4/SMPL_LEFT_arm_div4_0.01.msh",
        "point_selection": "/home/aa/Documents/GitHub/POLYFEM-DIR/deformable_obj/input_files/blender_obj_and_UVs/SMPL_left_arm/0.01/output/bc_files/cylinder_0.01_895_500_30.txt"
 
Attached .json

Simulation runs, but no forces are applied to the object.

Any ideas??
[cylinder_0.01_895_500_30_f_-100000_debug_json.txt](https://github.com/polyfem/polyfem/files/11011325/cylinder_0.01_895_500_30_f_-100000_debug_json.txt)

**Comment by teseoch** [comment]
so for point selection, it is the same format: `sideset_id vid`.

If you want to specify a value per node (not a commont function with the sidesets) you can specify a txt file in `dirichlet_boundary`, the format is `vid dx dy dz` in 3d and `vid dx dy` in 2d. `dx, dy, dz` are the displacements in the 3 directions
