### ISSUE TITLE
Number of points in *.vtu file is not the same as in *.msh 

### ISSUE THREAD

**Issue by antonagafonov** [polyfem/polyfem#177]
Hi,
I have *.msh file with 1657 vertices and 7039 tets.
After the simulation, I exported the *.vtu file, and it has 28156 points.I understand that this *.vtu file includes initial points positions also, deformation, and other information.

Question: which point_data is the initial point position (dimensions of the vector is [1657,3])

thanks

AA

Print the info about .msh and .vtu files.

mesh_data: <meshio mesh object>
  Number of points: 1657
  Number of cells:
    tetra: 7039
  Cell data: min_dihedral_angle
vtu_data: <meshio mesh object>
  Number of points: 28156
  Number of cells:
    tetra: 7039
  Point data: nodes, discr, scalar_value, tensor_value_11, tensor_value_12, tensor_value_13, tensor_value_21, tensor_value_22, tensor_value_23, tensor_value_31, tensor_value_32, tensor_value_33, scalar_value_avg, E, lambda, mu, nu, rho, body_ids, solution

**Comment by zfergus** [comment]
This is because PolyFEM saves an "unstitched" mesh (i.e., each cell has a copy of its vertices). For example, in a tet-mesh, you will get `4 * # tets` vertices.

**Comment by zfergus** [comment]
The vertices are all in their initial position. The deformation (displacement), velocity, acceleration, etc. are all stored as vertex data. You can use `meshio` in Python to access and play around with this data.

**Comment by antonagafonov** [comment]
I see,
Makes sense.

Thanks
