### ISSUE TITLE
build error on Mac OSX 10.14.4

### ISSUE THREAD

**Issue by ldXiao** [polyfem/polyfem#2]
Hi, thanks for creating this excellent package I manage to build it on ubuntu but failed on my Mac laptop.

When strictly following the instruction in tutorial 
make -j4 
would give some error message:
1 warning generated.
[ 91%] Building CXX object CMakeFiles/polyfem.dir/src/problem/MiscProblem.cpp.o
In file included from /Users/vector_cat/gits/polyfem/src/problem/KernelProblem.cpp:1:
In file included from /Users/vector_cat/gits/polyfem/build/include/polyfem/KernelProblem.hpp:3:
In file included from /Users/vector_cat/gits/polyfem/build/include/polyfem/ProblemWithSolution.hpp:3:
In file included from /Users/vector_cat/gits/polyfem/build/include/polyfem/Problem.hpp:4:
In file included from /Users/vector_cat/gits/polyfem/build/include/polyfem/ElementBases.hpp:6:
In file included from /Users/vector_cat/gits/polyfem/build/include/polyfem/Mesh.hpp:4:
In file included from /Users/vector_cat/gits/polyfem/build/include/polyfem/Common.hpp:24:
In file included from /Users/vector_cat/gits/polyfem/3rdparty/json/include/nlohmann/json.hpp:53:
/Users/vector_cat/gits/polyfem/3rdparty/json/include/nlohmann/detail/conversions/from_json.hpp:294:9: error: 
      static_assert failed "could not find from_json() method in T's namespace"
        static_assert(sizeof(BasicJsonType) == 0,
        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vector_cat/gits/polyfem/3rdparty/json/include/nlohmann/detail/conversions/from_json.hpp:309:16: note: 
      in instantiation of function template specialization
      'nlohmann::detail::from_json_fn::call<nlohmann::basic_json<std::map,
      std::vector, std::__1::basic_string<char>, bool, long long, unsigned long
      long, double, std::allocator, adl_serializer>,
      std::__1::basic_string_view<char, std::__1::char_traits<char> > >'
      requested here
        return call(j, val, priority_tag<1> {});
               ^
......
......
......
1 error generated.
make[2]: *** [CMakeFiles/polyfem.dir/src/problem/KernelProblem.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/polyfem.dir/all] Error 2
make: *** [all] Error 2

When running 
cmake --build ../cmake-build-debug --target polyfem -- -j 2

it will give another error message

In file included from /Users/vector_cat/gits/polyfem/3rdparty/geogram/src/lib/geogram/basic/string.h/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:49::64210:
:In file included from  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstring:61fatal error: :

/Users/vector_cat/gits/polyfem/3rdparty/geogram/src/lib/geogram/basic/string.h      :'geogram/basic/common.h'49 :file 10not: found 
fatal error: 
      'geogram/basic/common.h' file not found
#include <geogram/basic/common.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~
#include <geogram/basic/common.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
1 error generated.
make[3]: *** [CMakeFiles/polyfem.dir/3rdparty/Catch2/examples/000-CatchMain.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [CMakeFiles/polyfem.dir/3rdparty/Catch2/examples/010-TestCase.cpp.o] Error 1
make[2]: *** [CMakeFiles/polyfem.dir/all] Error 2
make[1]: *** [CMakeFiles/polyfem.dir/rule] Error 2
make: *** [polyfem] Error 2

Thanks in advance!

**Comment by teseoch** [comment]
it is strange, i develop on mac and it works.

for the error coming from `make` can you provide the full error.
The problem you reported is related to an external library not able to convert from a JSON object to some c++ type inside polyfem. Unfortuntelly the colprit line in polyfem is missing (it is something inside `KernelProblem`

For the second build, I never tried it. Is the log complete? From the error your reported I can see only the external part problem, is there other log with the error in polyfem?

**Comment by ldXiao** [comment]
Thanks for the quick reply and full error coming from `make` is
[ 91%] Building CXX object CMakeFiles/polyfem.dir/src/problem/MiscProblem.cpp.o
In file included from /Users/vector_cat/gits/polyfem/src/problem/KernelProblem.cpp:1:
In file included from /Users/vector_cat/gits/polyfem/build/include/polyfem/KernelProblem.hpp:3:
In file included from /Users/vector_cat/gits/polyfem/build/include/polyfem/ProblemWithSolution.hpp:3:
In file included from /Users/vector_cat/gits/polyfem/build/include/polyfem/Problem.hpp:4:
In file included from /Users/vector_cat/gits/polyfem/build/include/polyfem/ElementBases.hpp:6:
In file included from /Users/vector_cat/gits/polyfem/build/include/polyfem/Mesh.hpp:4:
In file included from /Users/vector_cat/gits/polyfem/build/include/polyfem/Common.hpp:24:
In file included from /Users/vector_cat/gits/polyfem/3rdparty/json/include/nlohmann/json.hpp:53:
/Users/vector_cat/gits/polyfem/3rdparty/json/include/nlohmann/detail/conversions/from_json.hpp:294:9: error: 
      static_assert failed "could not find from_json() method in T's namespace"
        static_assert(sizeof(BasicJsonType) == 0,
        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vector_cat/gits/polyfem/3rdparty/json/include/nlohmann/detail/conversions/from_json.hpp:309:16: note: 
      in instantiation of function template specialization
      'nlohmann::detail::from_json_fn::call<nlohmann::basic_json<std::map,
      std::vector, std::__1::basic_string<char>, bool, long long, unsigned long
      long, double, std::allocator, adl_serializer>,
      std::__1::basic_string_view<char, std::__1::char_traits<char> > >'
      requested here
        return call(j, val, priority_tag<1> {});
               ^
/Users/vector_cat/gits/polyfem/3rdparty/json/include/nlohmann/adl_serializer.hpp:26:9: note: 
      in instantiation of function template specialization
      'nlohmann::detail::from_json_fn::operator()<nlohmann::basic_json<std::map,
      std::vector, std::__1::basic_string<char>, bool, long long, unsigned long
      long, double, std::allocator, adl_serializer>,
      std::__1::basic_string_view<char, std::__1::char_traits<char> > >'
      requested here
        ::nlohmann::from_json(std::forward<BasicJsonType>(j), val);
        ^
/Users/vector_cat/gits/polyfem/3rdparty/json/include/nlohmann/json.hpp:2570:36: note: 
      in instantiation of function template specialization
      'nlohmann::adl_serializer<std::__1::basic_string_view<char,
      std::__1::char_traits<char> >, void>::from_json<const
      nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>,
      bool, long long, unsigned long long, double, std::allocator,
      adl_serializer> &, std::__1::basic_string_view<char,
      std::__1::char_traits<char> > >' requested here
        JSONSerializer<ValueType>::from_json(*this, ret);
                                   ^
/Users/vector_cat/gits/polyfem/3rdparty/json/include/nlohmann/json.hpp:2832:16: note: 
      in instantiation of function template specialization
      'nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>,
      bool, long long, unsigned long long, double, std::allocator,
      adl_serializer>::get<std::__1::basic_string_view<char,
      std::__1::char_traits<char> >, std::__1::basic_string_view<char,
      std::__1::char_traits<char> >, 0>' requested here
        return get<ValueType>();
               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:875:29: note: 
      in instantiation of function template specialization
      'nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>,
      bool, long long, unsigned long long, double, std::allocator,
      adl_serializer>::operator
      basic_string_view<std::__1::basic_string_view<char,
      std::__1::char_traits<char> >, 0>' requested here
        {__self_view __sv = __t; return assign(__sv);}
                            ^
/Users/vector_cat/gits/polyfem/src/problem/KernelProblem.cpp:163:17: note: in
      instantiation of function template specialization
      'std::__1::basic_string<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >::operator=<nlohmann::basic_json<std::map,
      std::vector, std::__1::basic_string<char>, bool, long long, unsigned long
      long, double, std::allocator, adl_serializer>, void>' requested here
                        formulation_ = params["formulation"];
                                     ^
1 error generated.
make[2]: *** [CMakeFiles/polyfem.dir/src/problem/KernelProblem.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/polyfem.dir/all] Error 2
make: *** [all] Error 2

As for the error from `cmake --build ../cmake-build-debug --target polyfem -- -j 2`, it is purely problem from external package.

**Comment by jdumas** [comment]
What version of clang/xcode are you using?

**Comment by ldXiao** [comment]
@jdumas 
```
$ clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0

$ /usr/bin/xcodebuild -version
Xcode 10.2.1
Build version 10E1001
 ```

**Comment by teseoch** [comment]
I just managed to reproduce the strange bug and committed something, can you check if it works?

**Comment by ldXiao** [comment]
@teseoch Hi, Teseo, It works now. Thanks!
