### ISSUE TITLE
Does the simulator supports .mesh file?

### ISSUE THREAD

**Issue by antonagafonov** [polyfem/polyfem#200]
Does the simulator supports *.mesh file?
Thanks AA

**Comment by antonagafonov** [comment]
Hi,
I am asking,because I am trying to simulate on *.msh file and getting the following error:

[2023-03-21 18:37:47.428] [polyfem] [debug] Building node mapping...
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at

I am not sure why this error happens...

**Comment by antonagafonov** [comment]
Hi,
I just pulled the latest version and compiled it, but I am still having the same issue.
I am unsure if this issue is caused by *.mesh file or some wrong bc that I am applying...
My *.jcon and bc files are the following.

Thanks
AA
[cylinder_0.01_936_514_10.txt](https://github.com/polyfem/polyfem/files/11039719/cylinder_0.01_936_514_10.txt)

[cylinder_0.01_936_514_10_f_-500_debug_json.txt](https://github.com/polyfem/polyfem/files/11039744/cylinder_0.01_936_514_10_f_-500_debug_json.txt)

**Comment by antonagafonov** [comment]
Hi,
This is a full report of a crash :

**Comment by antonagafonov** [comment]
Hi,
So I found where I am getting an error.
The error is in  Building Mesh faces to IDs stage.
the line is : in_primitive_to_primitive[in_offset + in_fi] = offset + faces_to_ids.at(in_face); // offset face ids

**Comment by antonagafonov** [comment]
Update...

commented this line 	
// in_primitive_to_primitive[in_offset + in_fi] =
// 	offset + faces_to_ids.at(in_face); // offset face ids

And now the simulation runs.

**Comment by zfergus** [comment]
Are you able to the `.mesh` file that causes this issue?

**Comment by antonagafonov** [comment]
Hi,
Uploading this *.mesh file.

[SMPL_LEFT_arm_div4.1.zip](https://github.com/polyfem/polyfem/files/11071646/SMPL_LEFT_arm_div4.1.zip)

**Comment by teseoch** [comment]
My guess is that the problem comes from the fact that you mesh has both volume and surface. I create a PR with a better fix on this: https://github.com/polyfem/polyfem/pull/205

Now instead of crashing it disables the feature

**Comment by antonagafonov** [comment]
Thanks, will try it.
