### ISSUE TITLE
Real-time simulation display

### ISSUE THREAD

**Issue by Alex-Beng** [polyfem/polyfem#202]
**Describe the solution you'd like**
I would like to request a new feature that allows real-time simulation display in the software. This feature will help users quickly identify solver errors and other issues without having to rely solely on log files. 

Thank you for considering this request!

**Additional context**

**Comment by teseoch** [comment]
Polyfem output a pvd file after every timestep, you could monitor that file.

Are you interested in more debug (eg inside the Newton iterations)?
