### ISSUE TITLE
Obstacle displacements based on vertex location sequence

### ISSUE THREAD

**Issue by jiangr100** [polyfem/polyfem#204]
Hello, 

I'd like to ask you if there exists a method to generate contact simulation based on the obstacle vertex location sequence (explicitly define where each vertex will be in each frame). I am currently using a single direction displacement only (by giving object displacement value) but it would be nice if the software can also support non-rigid deformation of the obstacles. 

Thank you.

**Comment by teseoch** [comment]
The obstacles are deformable, you can specify their displacement using a formula that depends on `x,y,z,t` as string.

If you want a sequence you can look at this example: https://github.com/polyfem/polyfem-data/blob/main/contact/examples/3D/mesh-sequence/kick.json

**Comment by jiangr100** [comment]
that is exactly what I'm looking for, thank you so much!
