### ISSUE TITLE
Unable to open VTU output

### ISSUE THREAD

**Issue by zfergus** [polyfem/polyfem#221]
**Describe the bug**
I cannot open the VTU files because there is something wrong with the "traction_force" point data.

```
ERROR: In vtkXMLDataReader.cxx, line 410
vtkXMLUnstructuredGridReader (0x126766390): Cannot read point data array "traction_force" from PointData in piece 0.  The data array in the element may be too short.
```

I know that [this](fa541ee245205014c833724061863b7df7c61ed4) commit works, so I think it was broken by #218.

**Platform**
- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by zfergus** [comment]
@arvigj can you take a look at this on Monday?

**Comment by arvigj** [comment]
#222 fixes this, I forgot to take obstacles into account.
