### ISSUE TITLE
Python Jupyter tutorial using Binder crashes

### ISSUE THREAD

**Issue by r03ert0** [polyfem/polyfem#26]
The python jupyter tutorial linked in the doc here https://polyfem.github.io/python/, which runs in Binder, crashes when trying to run the solver.

**Platform**
- [ ] Windows
- [x] MacOs: this is the computer I used to connect to Binder, but execution happens at Binder's servers, not in my computer
- [ ] Linux

(by the way, I started looking into this because I have exactly the same problem in my local installation: even for an extremely simple model – a grid and linear elasticity – the solver crashes)

**Comment by r03ert0** [comment]
never mind, now it works...

**Comment by antonagafonov** [comment]
Hi,
Could you share your solution?
Mine also crashes in pythonical version.

Thanks
