### ISSUE TITLE
Need Guidance on Running In-Timestep Remeshing

### ISSUE THREAD

**Issue by liuyulinn** [polyfem/polyfem#260]
## Description:

I'm interested in running In-Timestep Remeshing. Unfortunately, I couldn't find any existing scripts or documentation (e.g., JSON files or a README) that provide guidance on how to run it. I'm reaching out to get assistance and guidance on how to get started.

I appreciate your help in guiding me through the process of running In-timestep remeshing. Thank you!

**Comment by zfergus** [comment]
You can find the JSON input and meshes for the scenes shown in the paper [here](https://github.com/zfergus/in-timestep-remeshing-data). I plan to write a tutorial describing how to use it in detail, but I haven't found the time yet. Take a look at the scenes in the data repo and let me know if you have any issues or questions.

**Comment by liuyulinn** [comment]
Thanks for you help!

**Comment by liuyulinn** [comment]
I tried to run scripts in [in-timestep-remeshing-data](https://github.com/zfergus/in-timestep-remeshing-data), but it fails. 

I'm wondering if the "output/data" in 'scripts/common.json' is missing. If I keep the "output/data: ...", cases like twisting-cylinder.json can't work. But if we remove the "output/data: ..." part, the results seem not correct. 

For spikes2d, it fails at "Line search failed to find a valid finite energy step"; whereas for spikes3d, it gets stuck at splitting (for more than 30 minutes). 

I've tested it on 3 different machine, both Ubuntu 9.4.0-1ubuntu1~20.04.2, they all face the same problem. Can you give more instructions? Thanks for your help!

**Comment by zfergus** [comment]
I update the scripts to reflect the new JSON specification. I also moved some scripts into the folder `unused` to indicate they may not be maintained.

I adjusted the solver convergence tolerance for Spikes 2D so now it should work, and the latest commit to PolyFEM logs debug info about the remeshing progress which should help you debug the Spikes 3D.
