### ISSUE TITLE
installment failed: Could not find MKL_CORE_LIBRARY

### ISSUE THREAD

**Issue by zhiyunrichardpeng** [polyfem/polyfem#271]
**Describe the bug**
The installment of polyfem failed in my main linux workstation with a certain bug, but in another person's linux workstation, it passed this issue successfully. I wonder if you can help to shed some light on me about how to fix this issue. I collected the installment report of both machines as pasted below. I understand the c++ package in question is called "mkl" (Intel® oneAPI Math Kernel Library), which has something to do with CPU difference? (also I tried to install mkl library from intel's website, but after installing, I have no idea how to link the newly installed mkl library to the process of installing polyfem, and the bug below keeps occurring.) 

install process:

git clone https://github.com/polyfem/polyfem.git
cd polyfem
mkdir build
cd build
cmake ..   (failed)

bug report:
-- Third-party: creating target 'mkl::mkl'
-- MKL interface layer: lp64
-- MKL threading layer: tbb
-- MKL linking strategy: static
-- MKL version: 2021.3.0
-- CPM: polysolve: Adding package mkl-include@520 (520 at /local-scratch/localhome/zpa18/.cache/CPM/mkl-include/60ec474112fb209ca6af0f9352df943afe502964)
-- CPM: polysolve: Adding package mkl-static@520 (520 at /local-scratch/localhome/zpa18/.cache/CPM/mkl-static/174719a1cc8800b665e0eb8d1da7d94485076005)
-- MKL include dir: /local-scratch/localhome/zpa18/.cache/CPM/mkl-include/60ec474112fb209ca6af0f9352df943afe502964/include
CMake Error at /local-scratch/localhome/zpa18/.cache/CPM/polysolve/6ea77fbea1f302c4a39c6c8a78aec20f7ac8dda5/cmake/recipes/mkl.cmake:191 (message):
  Could not find MKL_CORE_LIBRARY
Call Stack (most recent call first):
  /local-scratch/localhome/zpa18/.cache/CPM/polysolve/6ea77fbea1f302c4a39c6c8a78aec20f7ac8dda5/cmake/recipes/mkl.cmake:226 (mkl_assert_is_found)
  /local-scratch/localhome/zpa18/.cache/CPM/polysolve/6ea77fbea1f302c4a39c6c8a78aec20f7ac8dda5/cmake/recipes/mkl.cmake:358 (mkl_add_imported_library)
  /local-scratch/localhome/zpa18/.cache/CPM/polysolve/6ea77fbea1f302c4a39c6c8a78aec20f7ac8dda5/cmake/recipes/blas.cmake:24 (include)
  /local-scratch/localhome/zpa18/.cache/CPM/polysolve/6ea77fbea1f302c4a39c6c8a78aec20f7ac8dda5/cmake/recipes/suitesparse.cmake:44 (include)
  /local-scratch/localhome/zpa18/.cache/CPM/polysolve/6ea77fbea1f302c4a39c6c8a78aec20f7ac8dda5/CMakeLists.txt:219 (include)

-- Configuring incomplete, errors occurred!

**Platform**
- [ ] Windows
- [ ] macOS
- [ 1] Linux, Ubuntu 22.04.3 LTS

**Comment by jdumas** [comment]
Could be a download issue with MKL. Can you try to delete your `local-scratch/localhome/zpa18/.cache/CPM/mkl-*` folders and rerun again to see if the problem persists?

**Comment by zhiyunrichardpeng** [comment]
> Could be a download issue with MKL. Can you try to delete your `local-scratch/localhome/zpa18/.cache/CPM/mkl-*` folders and rerun again to see if the problem persists?

Thanks very much! This solved my issue.
