### ISSUE TITLE
Best practice to use polyfem as external lib?

### ISSUE THREAD

**Issue by ldXiao** [polyfem/polyfem#3]
Dear all,

This might be a naive question and I am not even sure if it is a proper question to ask in GitHub issues.
I am trying to use polyfem as external lib in my project. Before this I have only used header only libs which provide guidance on how to use them as external libs. 
I naively included the `ployfem/build/include` directory and cmake would not generate errors at this stage, but then it will have difficulties finding the 3rdparty libs in polyfem itself.

What is the best practice to use polyfem as external lib or better, what should be put into FindPOLYFEM.cmake or polyfem.cmake to make it work?

Best Regards
Lind

**Comment by jdumas** [comment]
Hi. It should be enough to `add_subdirectory(<path-to-polyfem> polyfem)` in your cmake project, and then simply add `target_link_library(<your_target> polyfem)` in your cmake script. polyfem will download the dependencies that it needs with the version that it needs.

**Comment by ldXiao** [comment]
Oh, thanks! It works.
