### ISSUE TITLE
/output/data/rest_mesh outputs msh not obj

### ISSUE THREAD

**Issue by maxpaik16** [polyfem/polyfem#300]
When the /output/data/rest_mesh flagged is turned on, it outputs an msh file not an obj, even though the json spec describes it as outputting an obj. 

Platform: macOS

**Comment by zfergus** [comment]
The documentation is wrong then. It should be an MSH because this file type supports both triangle and tet meshes.

**Comment by maxpaik16** [comment]
Changed here: https://github.com/polyfem/polyfem/pull/301
