### ISSUE TITLE
Adding Mesh Based on Time for a Feeding Simulation

### ISSUE THREAD

**Issue by danimasa** [polyfem/polyfem#324]
**Describe the solution you'd like**
I'm simulating a system where feeding depends on time (likely the amount or rate of something being added). To achieve this, I need to dynamically add mesh elements (new objects) at specific points during the simulation after some determined time steps.

I've checked the existing code, but haven't found a way to add mesh elements during the simulation. Would it be difficult to implement a feature that allows adding mesh elements dynamically after some time steps?

**Comment by danimasa** [comment]
I did something similar to the remesh function:

```c++
void State::recurrent_mesh(int time_step, Eigen::MatrixXd &sol)
{
if(time_step == 1)
	return;

Eigen::MatrixXd old_sol = sol;
igl::Timer timer;
timer.start();

...

bool found = false;

for(auto &recurrent : recurrent_geometry)
{
	auto recurrent_time = recurrent["each_time_step"].get<int>();
	if (time_step % recurrent_time == 0) {
		found = true;
		read_single_fem_geometry(
			units,
			recurrent, args["root_path"],
			mesh, false);
	}
}

if (!found)
	return;

if (mesh == nullptr)
{
	log_and_throw_error("unable to load the mesh!");
}

...

build_basis();
assemble_rhs();
assemble_mass_mat();

// --------------------------------------------------------------------

const int old_ndof = ndof;
const int old_ndof_mesh = ndof_mesh;
const int old_ndof_obstacle = ndof_obstacle;

ndof_mesh = mesh->n_vertices() * dim;
ndof_obstacle = obstacle.n_vertices() * dim;
assert(ndof_obstacle == old_ndof_obstacle);
ndof = n_bases * dim;
assert(ndof == ndof_mesh + ndof_obstacle);

solve_data.rhs_assembler = build_rhs_assembler();

const Eigen::MatrixXd obstacle_sol = sol.bottomRows(ndof_obstacle);

if (ndof_obstacle > 0)
	sol.bottomRows(ndof_obstacle) = obstacle_sol;

sol.resize(ndof, 1);

logger().info("sol_norm: {}", sol.norm());

const double t0 = args["time"]["t0"];
const double dt = args["time"]["dt"];
const double time = t0 + time_step * dt;

init_nonlinear_tensor_solve(sol, time, /*init_time_integrator=*/true);
}
```
I'm calling it in the `solve_transient_tensor_nonlinear` function. But I'm getting an error `f(x) is nan or inf; stopping`. What could be the reason?

**Comment by zfergus** [comment]
Normally this error means there are intersections or inverted elements. Can you save the mesh and take a look?

**Comment by danimasa** [comment]
Yes, I plot the mesh and the added mesh was deformed, I changed the `resize` method for `conservativeResize` and added the obstacle mesh in the end of the matrix. Now I can run the simulation. Thanks.

**Comment by zfergus** [comment]
Awesome! Feel free to create a PR with your changes anytime if you find them useful.
