### ISSUE TITLE
PolyFEM_bin Crash On Any 3D Mesh

### ISSUE THREAD

**Issue by esotericDisciple** [polyfem/polyfem#4]
I tried both models from the VegaFEM and LibIGL/tutorial/shared projects and aside from 2triangles.off, the program crashes on either "Build basis" with a segfault on  a call to `polyfem::Navigation3D::get_index_from_element_face(polyfem::Mesh3DStorage const&, int) ()`
Or I can check on "spline basis" which gets me as far as "Build vis mesh," but then it will crash on "Assign Rhs" with no hint in gdb as to where and why it happens; all I get is:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

```

**Comment by jdumas** [comment]
Are you trying to solve a 2D or 3D problem?  If the latter, you need to provide a tetrahedral mesh (.mesh should work).

**Comment by esotericDisciple** [comment]
Couldn't say what "2d/3d problem" it was...I just repeated the steps on the tutorial page at https://polyfem.github.io/tutorial/ but switched out the holed plate mesh with one from libIGL/vegaFEM, which are mostly the same meshes every researcher seems to use (The Stanford Armadillo, The Stanford Bunny, etc). I thought such meshes were already tetrahedralized and I have no idea what I'm doing other than just randomly changing settings hoping the binary won't crash...

**Comment by teseoch** [comment]
Polyfem **doest not** tetrahedralize meshes.

If you load a triangle mesh it assumes it is a **planar** mesh.
If you are trying to solve a volumetric problem (e.g., bunny, armadillo, etc) you need to first thetrahedralize the meshes. You can use tetgen or [TetWild](https://github.com/Yixin-Hu/TetWild).
