### ISSUE TITLE
Varying stiffness and periodic boundary conditions

### ISSUE THREAD

**Issue by Getshi** [polyfem/polyfem#6]
Dear all,

I am looking for a way to do nonlinear elastostatics with varying stiffness (e.g. per tet) and subject to boundary conditions of the form `u_right = A(x) u_left`, where `A` is a spatially varying 3x3 matrix and `u_right, u_left` are displacements on opposite sides of the mesh.
Since I couldn't find tutorials or code on either varying stiffness or periodic boundaries I was curious if this is something that is or will be supported at all, or if I could do some minor modifications in the code to get it working for myself within either c++ or python.

Best Georg

**Comment by teseoch** [comment]
Hi,

I just pushed on C++ a beta feature to support varying stiffness. I dont have data to test it but it should work.

to use it specify in the json an array of Es and nus per tet. 
**Note** it works only for linear elasticity. If it produces resasonable results i will integrate it in the rest of the models

for the periodic bc i have to think :D

**Comment by Getshi** [comment]
Hi! Thanks for the quickfix.
For my purposes I really do need the periodic conditions and it might actually be even more difficult, requiring some Lagrange multipliers.
I think I could do my own constrained Newton solver in Eigen using some code I already have lying around, but I'd need to be able to evaluate energy, gradient and hessian and understand which DoF corresponds to which vertex with getters/setters and such.
It's not high priority for me, so don't worry about it if it's just for me alone :)

**Comment by teseoch** [comment]
Multimaterial has been added
