### ISSUE TITLE
Question about HYPRE

### ISSUE THREAD

**Issue by h00shi** [polyfem/polyfem#7]
This is a question rather than an issue. Sorry if it is out of place.

I noticed that you have used HYPRE. Algebraic multigrid is something that I have always wanted to try but never found the time to. I am just curios, do you have any insight on how it compares to the defacto solver of `GMRES + ILU(0) preconditioning + RCM re-ordering` for problems like (non-)linear elasticity or Poisson?

**Comment by teseoch** [comment]
I have no idea.

We also use "copy pasted" example form the documentation which is maybe the the best option.
For instance, it is unable to solve stokes problems.

The solver part is pretty independent and you can find the hypre eigen wrapper here if you want to play around:
https://github.com/polyfem/polyfem/blob/master/src/solver/LinearSolverHypre.cpp

Something I tried is to change CG preconditioner with BiCG and there was little difference.

Let me know if you find something interesting 😄

**Comment by h00shi** [comment]
Thanks. Now I am getting motivated to try out these solver ideas on some of your test problems.

**Comment by teseoch** [comment]
I recently separated PolyFEM solvers in a separate independent library.
Check it out here: https://github.com/polyfem/polysolve
