### ISSUE TITLE
Example of surface selection with a file

### ISSUE THREAD

**Issue by sdast9** [polyfem/polyfem#86]
I love all of the work you have been doing recently. However, I noticed that the BC_setter does not exist anymore and that the website now says "* a file path containing one ID per surface element" when referring to surface element selection. I was wondering if you could provide details on that file. Is it a text file or JSON? What does the format look like? Does a "surface element" refer to a surface triange (assuming tets for the solid geometry) or could it be a vertex? I looked through your examples and I didn't see one that included a case like this. Thanks in advance!

**Comment by teseoch** [comment]
the bc setter is on a separate repo: https://github.com/polyfem/app-and-misc
that file is what the bc setter outputs
