### ISSUE TITLE
Multimaterial

### ISSUE THREAD

**Issue by sdast9** [polyfem/polyfem#90]
Thanks for the reply to my other question. Here is another. I'm learning C++ (slowly), primarily because I'm motivated by the IPC work and polyfem. However, I'm still not very confident. With that said, I tried going through your multimaterial example and couldn't get it to work. All three entities of the .msh file were getting assigned to the same volume #, so I could not assign different materials to them. I tracked it down to the else statement in the geometryreader.cpp (~lines 388-392; sorry I'm on my phone without access to my computer). If  I comment out those lines, the code maintains the volumes assigned from the entities in the .msh file. I didn't test to see if that breaks other examples, so I figured it is best for you to have a look. 

**Platform**
- [ ] Windows
- [x] macOS
- [x] Linux

**Comment by zfergus** [comment]
I am going to close this issue and open a separate one for the heterogenous element order problem.
