### ISSUE TITLE
Tutorials - Getting started json not working

### ISSUE THREAD

**Issue by fortoboy** [polyfem/polyfem#99]
Hello, I am using a MacBook Pro (OSX 12.5.1), and compiled PolyFEM with no problems. However, when trying to run through the tutorial (https://polyfem.github.io/tutorials/getting_started/) I am having issues. First, when running the first run.json problem I get this error:
> PolyFEM_bin --json run.json
libc++abi: terminating with uncaught exception of type nlohmann::detail::parse_error: [json.exception.parse_error.101] parse error at line 12, column 5: syntax error while parsing object separator - unexpected '}'; expected ':'
zsh: abort      PolyFEM_bin --json run.json

When I choose "Refer to the [JSON API](https://polyfem.github.io/tutorials/json) for a the full description of JSON parameters." this link appears to take me to a page that is not displaying correctly on my chrome browser (I attached a screenshot). However after reading (https://polyfem.github.io/json/) I changed the output line of the run.json but got a new error:
    "output": {
        "stats.json" --> "json": "stats.json",
    },
new error:
>PolyFEM_bin --json run.json
[2022-08-23 15:24:15.786] [polyfem] [error] invalid input json, error error: No valid rules in this list:{"default":"skip","doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"Linear"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"Quadratic"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"Cubic"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"Sine"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"Franke"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"FrankeOld"}
{"doc":"TODO","optional":["func"],"pointer":"/preset_problem","required":["type"],"type":"object","type_name":"GenericScalarExact"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"Zero_BC"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"Elastic"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"Walk"}
{"doc":"TODO","optional":["axis_coordiante","n_turns","fixed_boundary","turning_boundary","bbox_center"],"pointer":"/preset_problem","required":["type"],"type":"object","type_name":"TorsionElastic"}
{"doc":"TODO","optional":["axis_coordiante0","axis_coordiante1","angular_v0","angular_v1","turning_boundary0","turning_boundary1","bbox_center"],"pointer":"/preset_problem","required":["type"],"type":"object","type_name":"DoubleTorsionElastic"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"ElasticZeroBC"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"ElasticExact"}
{"doc":"TODO, add displacement, E, nu, formulation, mesh_size","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"ElasticCantileverExact"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"CompressionElasticExact"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"QuadraticElasticExact"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"LinearElasticExact"}
{"doc":"TODO, add optionals","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"PointBasedTensor"}
{"doc":"TODO, add optionals","optional":["formulation","n_kernels","kernel_distance","kernel_weights"],"pointer":"/preset_problem","required":["type"],"type":"object","type_name":"Kernel"}
{"doc":"TODO, add optionals","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"Node"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"TimeDependentScalar"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"MinSurf"}
{"doc":"TODO","optional":["force"],"pointer":"/preset_problem","required":["type"],"type":"object","type_name":"Gravity"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"ConstantVelocity"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"TwoSpheres"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"DrivenCavity"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"DrivenCavityC0"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"DrivenCavitySmooth"}
{"doc":"TODO, add inflow, outflow, inflow_amout, outflow_amout, direction, obstacle","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"Flow"}
{"doc":"TODO","optional":["U"],"pointer":"/preset_problem","required":["type"],"type":"object","type_name":"FlowWithObstacle"}
{"doc":"TODO","optional":["U","time_dependent"],"pointer":"/preset_problem","required":["type"],"type":"object","type_name":"CornerFlow"}
{"doc":"TODO, add inflow_id, direction, no_slip","optional":["U"],"pointer":"/preset_problem","required":["type"],"type":"object","type_name":"UnitFlowWithObstacle"}
{"doc":"TODO, add radius","optional":["time_dependent","viscosity"],"pointer":"/preset_problem","required":["type"],"type":"object","type_name":"StokesLaw"}
{"doc":"TODO","optional":["viscosity"],"pointer":"/preset_problem","required":["type"],"type":"object","type_name":"TaylorGreenVortex"}
{"doc":"TODO","optional":["func"],"pointer":"/preset_problem","required":["type"],"type":"object","type_name":"SimpleStokeProblemExact"}
{"doc":"TODO","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"SineStokeProblemExact"}
{"doc":"TODO","optional":["func","viscosity"],"pointer":"/preset_problem","required":["type"],"type":"object","type_name":"TransientStokeProblemExact"}
{"doc":"TODO","optional":["time_dependent","viscosity"],"pointer":"/preset_problem","required":["type"],"type":"object","type_name":"Kovnaszy"}
{"doc":"TODO","optional":["time_dependent"],"pointer":"/preset_problem","required":["type"],"type":"object","type_name":"Airfoil"}
{"doc":"TODO","optional":["U","time_dependent"],"pointer":"/preset_problem","required":["type"],"type":"object","type_name":"Lshape"}
{"doc":"TODO, type, omega, is_scalar","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"TestProblem"}
{"doc":"TODO, type, omega, is_scalar","pointer":"/preset_problem","required":["type"],"type":"object","type_name":"BilaplacianProblemWithSolution"}

libc++abi: terminating with uncaught exception of type std::runtime_error: Invald input json file
zsh: abort      PolyFEM_bin --json run.json

**Platform**
- [ ] Windows
- [X] macOS
- [ ] Linux

<img width="1437" alt="Screen Shot 2022-08-23 at 3 30 22 PM" src="https://user-images.githubusercontent.com/5419916/186249473-938a0120-a118-44d8-aa12-568b94bc1814.png">

**Comment by zfergus** [comment]
I fixed the website's broken links and "getting started" JSON example. The other error is that it should be 
```
"preset_problem": {
    "type": "Franke"
},
```
(i.e., `"name"` -> `"type"`).

We also recently published the full JSON API specification [here](https://polyfem.github.io/json_api/).

**Comment by zfergus** [comment]
I closed the issue for now. Feel free to reopen if you run into any other problems.

**Comment by fortoboy** [comment]
Thanks for getting back to me! However, I have to reopen it because it looks like the solution doesn't make sense. So it runs now with the updated json file, but the solution field is a constant scalar everywhere (unlike the tutorial image) and a small caveat:
 the <> in the "file_name": field comes through to the output filename and probably should be removed in the json file:
            "file_name": "<result.vtu>" --> "file_name": "result.vtu"

<img width="750" alt="Screen Shot 2022-08-31 at 11 37 59 AM" src="https://user-images.githubusercontent.com/5419916/187720004-0f4f0206-a441-4e89-9b15-64240fc50deb.png">

**Comment by fortoboy** [comment]
Sorry, it looks like you cannot reopen issues, I can file a new one and reference this one if no one gets notifications.

**Comment by fortoboy** [comment]
Just an FYI, I am running /Volumes/SamsungSSD_1TB/polyfem/data/contact/examples/3D/large-ratios/sphere-mat.json example with no problem (I can see the output displacement/deformation looks correct). So it doesn't seem to be an installation or computer issue.

**Comment by zfergus** [comment]
Can you try running the plate-hole example using the `mass-quadrature` branch? That branch contains a fix for the mass matrix (`main` uses too small of a quadrature order). I wonder if the problem you see is because the mass matrix is incorrect.

**Comment by fortoboy** [comment]
Using the mass-quadrature branch i get a similar problem, different result number and error message but same problem:
[2022-08-31 15:49:11.411] [polyfem] [info] Hypre...
[2022-08-31 15:49:11.464] [polyfem] [error] Solver error: 1.0904650679346017

<img width="731" alt="Screen Shot 2022-08-31 at 3 49 52 PM" src="https://user-images.githubusercontent.com/5419916/187769457-4bbb7f03-b009-4d2e-931b-1fc9f5d9c051.png">

**Comment by zfergus** [comment]
I figured this one out. The issue is the surface selection by default now is empty (still need to update the tutorial). This broke this example because it was expecting a surface selection to apply the boundary conditions. 

You can find a working version [here](https://github.com/polyfem/polyfem-data/blob/main/standard/plate_hole.json) where I have manually set up the surface selection to match the old default.

The other issue was the mesh needed to be normalized to get the expected result.

Here is what I get when I run the simulation file linked above:

![image](https://user-images.githubusercontent.com/8219522/188799580-b9d768ab-7e29-4461-b879-c75a0bfd50b2.png)

Let us know if you run into any other issues.
